### ISSUE TITLE
Move Justin’s new nb in p&d repo?

### ISSUE THREAD

**Issue by timothybeal** [hlab-repo/purity-and-danger#2]
@jobarber @textpotential is ok to do so? We could then also move over diff csv files as we try diff tweaks.

**Comment by jobarber** [comment]
Yes! Sorry. I forgot to to do this. I can do it a little later today if you want me to do so.

**Comment by jobarber** [comment]
I moved both notebooks over from colab. Great idea on the csvs and tweaks.

**Comment by jobarber** [comment]
The notebooks are not viewable in GitHub at the moment, but I believe this is due to a problem on GitHub's end.

**Comment by jobarber** [comment]
The notebooks are now viewable in GitHub.

**Comment by timothybeal** [comment]
Great. If we simply rename the file in the last line `to_csv('immigration.csv')` that will prevent overwriting, yes?

**Comment by jobarber** [comment]
Yes!
