### ISSUE TITLE
Paid?

### ISSUE THREAD

**Issue by timothybeal** [hlab-repo/purity-and-danger#3]
Have you two @textpotential @jobarber been paid for this grant yet? Not from Case but from the von Humboldt people? If not I need to get Mark to do that right away. The Germans apparently disappear end May.

**Comment by jobarber** [comment]
I have not yet, but I have wondered if they need to see results first.

**Comment by timothybeal** [comment]
Apparently they don’t 


Timothy Beal
Florence Harkness Professor of Religion
Chair, Department of Religious Studies
Director, h.lab
Case Western Reserve University

**Comment by textpotential** [comment]
Same. I don’t remember seeing anything.

**Comment by timothybeal** [comment]
I think that it's not necessary to deliver code etc to get this done; all it needs is Mark to approve, which either he already did last fall or will do when he emails the professor at Onusbruck

**Comment by jobarber** [comment]
Thanks, @timothybeal . I still plan to get something useful done by the end of May (generalizable to other problems but hopefully producing good data for us on purity and danger).

**Comment by textpotential** [comment]
We have both now been paid from the Germans.
